// examples/min-react-js-chat/src/App.js
import './App.css';
import { Waku, WakuMessage } from 'js-waku';
import * as React from 'react';
import protons from 'protons';

const ContentTopic = `/min-react-js-chat/1/chat/proto`;

const proto = protons(`
message SimpleChatMessage {
  uint64 timestamp = 1;
  string text = 2;
}
`);

function App() {
  const [waku, setWaku] = React.useState(undefined);
  const [wakuStatus, setWakuStatus] = React.useState('None');
  const [sendCounter, setSendCounter] = React.useState(0);
  const [messages, setMessages] = React.useState([]);

  React.useEffect(() => {
    if (!!waku) return;
    if (wakuStatus !== 'None') return;

    setWakuStatus('Starting');

    Waku.create({ bootstrap: true }).then((waku) => {
      setWaku(waku);
      setWakuStatus('Connecting');
      waku.waitForConnectedPeer().then(() => {
        setWakuStatus('Ready');
      });
    });
  }, [waku, wakuStatus]);

  // Need to keep the same reference around to add and delete from relay observer
  const processIncomingMessage = React.useCallback((wakuMessage) => {
    if (!wakuMessage.payload) return;

    const { text, timestamp } = proto.SimpleChatMessage.decode(
      wakuMessage.payload
    );

    const time = new Date();
    time.setTime(timestamp);
    const message = { text, timestamp: time };

    setMessages((currMessages) => {
      return [message].concat(currMessages);
    });
  }, []);

  React.useEffect(() => {
    if (!waku) return;

    waku.relay.addObserver(processIncomingMessage, [ContentTopic]);

    return function cleanUp() {
      waku.relay.deleteObserver(processIncomingMessage, [ContentTopic]);
    };
  }, [waku, wakuStatus, processIncomingMessage]);

  const sendMessageOnClick = () => {
    if (wakuStatus !== 'Ready') return;

    sendMessage(`Here is message #${sendCounter}`, new Date(), waku).then(() =>
      console.log('Message sent')
    );

    setSendCounter(sendCounter + 1);
  };

  return (
    <div className="App">
      <header className="App-header">
        <p>{wakuStatus}</p>
        <button onClick={sendMessageOnClick} disabled={wakuStatus !== 'Ready'}>
          Send Message
        </button>
        <ul>
          {messages.map((msg) => {
            return (
              <li>
                <p>
                  {msg.timestamp.toString()}: {msg.text}
                </p>
              </li>
            );
          })}
        </ul>
      </header>
    </div>
  );
}

export default App;

function sendMessage(message, timestamp, waku) {
  const time = timestamp.getTime();

  const payload = proto.SimpleChatMessage.encode({
    timestamp: time,
    text: message,
  });

  return WakuMessage.fromBytes(payload, ContentTopic).then((wakuMessage) =>
    waku.relay.send(wakuMessage)
  );
}

// examples/relay-angular-chat/src/app/app.component.ts
import { Component } from '@angular/core';
import { Waku, WakuMessage } from 'js-waku';
import protons from "protons";

const proto = protons(`
message SimpleChatMessage {
  uint64 timestamp = 1;
  string text = 2;
}
`);

interface MessageInterface {
  timestamp: Date,
  text: string
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})

export class AppComponent {
  
  contentTopic: string = `/relay-angular-chat/1/chat/proto`;
  messages: MessageInterface[] = [];
  messageCount: number = 0;
  title: string = 'relay-angular-chat';
  waku!: Waku;
  wakuStatus: string = 'None';

  ngOnInit(): void {
    Waku.create({ bootstrap: { default: true } }).then((waku) => {
      this.wakuStatus = 'Connecting...'
      
      waku.waitForRemotePeer().then(() => {
        this.wakuStatus = 'Connected';
        this.waku = waku;

        this.waku.relay.addObserver(this.processIncomingMessages, [this.contentTopic]);
      });
    });
  }
  
  ngOnDestroy(): void {
    this.waku.relay.deleteObserver(this.processIncomingMessages, [this.contentTopic]);
  }

  processIncomingMessages = (wakuMessage: WakuMessage) => {
    if (!wakuMessage.payload) return;

    const { timestamp, text } = proto.SimpleChatMessage.decode(
      wakuMessage.payload
    );
    const time = new Date();
    time.setTime(timestamp);
    const message = { text, timestamp: time };

    this.messages.push(message);
  }

  send(message: string, waku: object, timestamp: Date) {
    const time = timestamp.getTime();

    const payload = proto.SimpleChatMessage.encode({
      timestamp: time,
      text: message,
    });

    return WakuMessage.fromBytes(payload, this.contentTopic).then((wakuMessage) => {
      this.waku.relay.send(wakuMessage);
    });
  }
  
  sendMessageOnClick(): void {
    this.send(`Here is a message #${this.messageCount}`, this.waku, new Date()).then(() => {
      console.log(`Message #${this.messageCount} sent`);
      this.messageCount += 1;
    });
  }
}

<h1>{{title}}</h1>
<p>Waku node's status: {{ wakuStatus }}</p>
<button (click)="sendMessageOnClick()" [disabled]="wakuStatus !== 'Connected'">Send Message</button>
<h2>Messages</h2>
<ul class="messages">
  <li *ngFor="let message of messages">
      <span class="badge">{{ message.timestamp }}</span>
      <span class="name">{{ message.text }}</span>
  </li>
</ul>
