// examples/relay-angular-chat/src/app/app.component.ts
import { Component } from '@angular/core';
import { Waku, WakuMessage } from 'js-waku';
import protons from "protons";

const proto = protons(`
message SimpleChatMessage {
  uint64 timestamp = 1;
  string text = 2;
}
`);

interface MessageInterface {
  timestamp: Date,
  text: string
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})

export class AppComponent {
  
  contentTopic: string = `/relay-angular-chat/1/chat/proto`;
  messages: MessageInterface[] = [];
  messageCount: number = 0;
  title: string = 'relay-angular-chat';
  waku!: Waku;
  wakuStatus: string = 'None';

  ngOnInit(): void {
    Waku.create({ bootstrap: { default: true } }).then((waku) => {
      this.wakuStatus = 'Connecting...'
      
      waku.waitForRemotePeer().then(() => {
        this.wakuStatus = 'Connected';
        this.waku = waku;

        this.waku.relay.addObserver(this.processIncomingMessages, [this.contentTopic]);
      });
    });
  }
  
  ngOnDestroy(): void {
    this.waku.relay.deleteObserver(this.processIncomingMessages, [this.contentTopic]);
  }

  processIncomingMessages = (wakuMessage: WakuMessage) => {
    if (!wakuMessage.payload) return;

    const { timestamp, text } = proto.SimpleChatMessage.decode(
      wakuMessage.payload
    );
    const time = new Date();
    time.setTime(timestamp);
    const message = { text, timestamp: time };

    this.messages.push(message);
  }

  send(message: string, waku: object, timestamp: Date) {
    const time = timestamp.getTime();

    const payload = proto.SimpleChatMessage.encode({
      timestamp: time,
      text: message,
    });

    return WakuMessage.fromBytes(payload, this.contentTopic).then((wakuMessage) => {
      this.waku.relay.send(wakuMessage);
    });
  }
  
  sendMessageOnClick(): void {
    this.send(`Here is a message #${this.messageCount}`, this.waku, new Date()).then(() => {
      console.log(`Message #${this.messageCount} sent`);
      this.messageCount += 1;
    });
  }
}

<h1>{{title}}</h1>
<p>Waku node's status: {{ wakuStatus }}</p>
<button (click)="sendMessageOnClick()" [disabled]="wakuStatus !== 'Connected'">Send Message</button>
<h2>Messages</h2>
<ul class="messages">
  <li *ngFor="let message of messages">
      <span class="badge">{{ message.timestamp }}</span>
      <span class="name">{{ message.text }}</span>
  </li>
</ul>

// examples/relay-reactjs-chat/src/App.js
import { Waku } from 'js-waku';
import * as React from 'react';
import protons from 'protons';
import { WakuMessage } from 'js-waku';

const ContentTopic = `/relay-reactjs-chat/1/chat/proto`;

const proto = protons(`
message SimpleChatMessage {
  uint64 timestamp = 1;
  string text = 2;
}
`);

function App() {
  const [waku, setWaku] = React.useState(undefined);
  const [wakuStatus, setWakuStatus] = React.useState('None');
  // Using a counter just for the messages to be different
  const [sendCounter, setSendCounter] = React.useState(0);

  React.useEffect(() => {
    if (!!waku) return;
    if (wakuStatus !== 'None') return;

    setWakuStatus('Starting');

    Waku.create({ bootstrap: true }).then((waku) => {
      setWaku(waku);
      setWakuStatus('Connecting');
      waku.waitForConnectedPeer().then(() => {
        setWakuStatus('Ready');
      });
    });
  }, [waku, wakuStatus]);

  const sendMessageOnClick = () => {
    // Check Waku is started and connected first.
    if (wakuStatus !== 'Ready') return;

    sendMessage(`Here is message #${sendCounter}`, waku, new Date()).then(() =>
      console.log('Message sent')
    );

    // For demonstration purposes.
    setSendCounter(sendCounter + 1);
  };

  return (
    <div className="App">
      <header className="App-header">
        <p>{wakuStatus}</p>
        <button onClick={sendMessageOnClick} disabled={wakuStatus !== 'Ready'}>
          Send Message
        </button>
      </header>
    </div>
  );
}

function sendMessage(message, waku, timestamp) {
  const time = timestamp.getTime();

  // Encode to protobuf
  const payload = proto.SimpleChatMessage.encode({
    timestamp: time,
    text: message
  });

  // Wrap in a Waku Message
  return WakuMessage.fromBytes(payload, ContentTopic).then((wakuMessage) =>
    // Send over Waku Relay
    waku.relay.send(wakuMessage)
  );
}

export default App;
